version: '3.7'

services:
  app:
    build: ./
    command: ./cmd/main
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    restart: always
    environment:
      POSTGRES_DB: "avitodb"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "avitosecret"

  database:
    image: "postgres:15"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "avitodb"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "avitosecret"
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5436:5432"