version: '3.7'

services:
  app:
    build: ./
    command: ./wait-for-postgres.sh db ./cmd/main
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      POSTGRES_DB: "avitodb"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "avitosecret"

  database:
    image: "postgres:15"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_DB: "avitodb"
      POSTGRES_USER: "avito"
      POSTGRES_PASSWORD: "avitosecret"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - "5436:5432"